- name: Gather the package facts
  ansible.builtin.package_facts:
    manager: auto

- name: Print the package facts
  ansible.builtin.debug:
    var: ansible_facts.packages

- name: Run GCloud installation
  become: true
  apt:
    name: google-cloud-cli
    state: latest
    update_cache: yes
  when: "not 'gcloud' in ansible_facts.packages"