- name: Install the HashiCorp GPG key
  become: true
  ansible.builtin.shell: wget --quiet --output-document - https://apt.releases.hashicorp.com/gpg | gpg --no-default-keyring --keyring gnupg-ring:/usr/share/keyrings/hashicorp-archive-keyring.gpg --import

- name: Change key permissions
  file:
    path: /usr/share/keyrings/hashicorp-archive-keyring.gpg
    mode: 'go+r'

- name: Check if package source exist
  become: true
  ansible.builtin.stat:
    path: /etc/apt/sources.list.d/hashicorp.list
  register: package_source

- name: Add the official HashiCorp repository to the system
  become: true
  ansible.builtin.shell: echo "deb https://apt.releases.hashicorp.com $(lsb_release -cs) main" | tee /etc/apt/sources.list.d/hashicorp.list
  when: not package_source.stat.exists

