- name: Install the HashiCorp GPG key
  become: true
  ansible.builtin.apt_key:
    url: https://apt.releases.hashicorp.com/gpg

- name: Check if package source exist
  become: true
  ansible.builtin.stat:
    path: /etc/apt/sources.list.d/hashicorp.list
  register: package_source

- name: Add the official HashiCorp repository to the system
  become: true
  ansible.builtin.shell: echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | tee /etc/apt/sources.list.d/hashicorp.list
  when: not package_source.stat.exists
