- name: Install dependencies for GCloud CLI
  become: true
  apt:
    pkg:
      - 'apt-transport-https'
      - 'ca-certificates'
      - 'gnupg'
      - 'snapd'
    state: latest
#     update_cache: true
