- name: Check if Oh-My-ZSH is already installed
  become: true
  ansible.builtin.stat:
    path: /root/.oh-my-zsh
  register: file

- name: Run Oh-My-ZSH installation
  become: true
  shell: "sh -c '$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)'"
  when: not file.stat.exists
