- name: Check if Oh-My-ZSH is already installed
  ansible.builtin.stat:
    path: "/{{ lookup('env','USER') }}/.oh-my-zsh"
  register: file

- name: Run Oh-My-ZSH installation
  shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  when: not file.stat.exists
  async: 2100
  poll: 0
  register: omz_install
