- name: Allow switch shell
  become: true
  shell:
    cmd: sed -i "s/auth       required   pam_shells.so/auth       sufficient   pam_shells.so/" /etc/pam.d/chsh 

- name: Select ZSH as default
  shell:
    cmd: chsh $USER -s $(which zsh) && echo exec zsh >> ~/.bashrc 
